apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx #can be different
    tier: frontend
spec:
  selector:
    matchLabels:
      app: myapp #should be same
  replicas: 6
  template:
    metadata:
      name: nginx
      labels:
        app: myapp #should be same
    spec:
      containers:
        - name: nginx-container1
          image: nginx
